"""esquema inicial

Revision ID: 48978732de6a
Revises: 
Create Date: 2026-09-18 10:56:35.542515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48978732de6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_corto', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instruccion_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_codigo_corto'), 'areas', ['codigo_corto'], unique=False)
    op.create_index(op.f('ix_areas_tenant_id'), 'areas', ['tenant_id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_tenant_id'), 'empresas', ['tenant_id'], unique=True)
    op.create_table('plantillas_evaluacion',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_evaluacion_tenant_id'), 'plantillas_evaluacion', ['tenant_id'], unique=False)
    op.create_table('tags',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tenant_id'), 'tags', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'RECLUTADOR', 'EVALUADOR', 'GERENTE', name='rolusuario'), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('dimensiones_evaluacion',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plantilla_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('puntaje_maximo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensiones_evaluacion_plantilla_id'), 'dimensiones_evaluacion', ['plantilla_id'], unique=False)
    op.create_index(op.f('ix_dimensiones_evaluacion_tenant_id'), 'dimensiones_evaluacion', ['tenant_id'], unique=False)
    op.create_table('vacantes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsabilidades', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requisitos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requisitos_deseables', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('beneficios', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('habilidades', sa.JSON(), nullable=True),
    sa.Column('tecnologias', sa.JSON(), nullable=True),
    sa.Column('nivel_experiencia', sa.Enum('PRACTICANTE', 'JUNIOR', 'SEMI_SENIOR', 'SENIOR', 'LIDER', name='nivelexperiencia'), nullable=True),
    sa.Column('anios_experiencia', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'REMOTO', 'HIBRIDO', name='modalidad'), nullable=True),
    sa.Column('tipo_contrato', sa.Enum('INDEFINIDO', 'PLAZO_FIJO', 'PRACTICAS', 'FREELANCE', 'PART_TIME', name='tipocontrato'), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salario_minimo', sa.Float(), nullable=True),
    sa.Column('salario_maximo', sa.Float(), nullable=True),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('mostrar_salario', sa.Boolean(), nullable=False),
    sa.Column('confidencial', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'ABIERTA', 'PAUSADA', 'CERRADA', name='estadovacante'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadvacante'), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('jefe_directo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('solicitante', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cantidad_posiciones', sa.Integer(), nullable=False),
    sa.Column('score_cv_minimo', sa.Integer(), nullable=False),
    sa.Column('nota_minima_examen', sa.Integer(), nullable=False),
    sa.Column('top_candidatos_finalistas', sa.Integer(), nullable=False),
    sa.Column('instruccion_ia_extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacantes_area_id'), 'vacantes', ['area_id'], unique=False)
    op.create_index(op.f('ix_vacantes_codigo'), 'vacantes', ['codigo'], unique=True)
    op.create_index(op.f('ix_vacantes_estado'), 'vacantes', ['estado'], unique=False)
    op.create_index(op.f('ix_vacantes_tenant_id'), 'vacantes', ['tenant_id'], unique=False)
    op.create_table('candidatos',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cv_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('POSTULADO', 'CV_ANALIZANDO', 'CV_APROBADO', 'CV_RECHAZADO', 'EXAMEN_PENDIENTE', 'EXAMEN_RENDIDO', 'EXAMEN_APROBADO', 'EXAMEN_RECHAZADO', 'ENTREVISTA_PENDIENTE', 'ENTREVISTA_REALIZADA', 'FINALISTA', 'CONTRATADO', 'DESCARTADO', name='estadocandidato'), nullable=False),
    sa.Column('es_finalista', sa.Boolean(), nullable=False),
    sa.Column('pretension_salarial', sa.Float(), nullable=True),
    sa.Column('score_cv', sa.Integer(), nullable=True),
    sa.Column('match_porcentaje', sa.Float(), nullable=True),
    sa.Column('clasificacion_ia', sa.Enum('ALTAMENTE_RECOMENDADO', 'RECOMENDADO', 'REQUIERE_REVISION', 'NO_APTO', name='clasificacionia'), nullable=True),
    sa.Column('resumen_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('habilidades_detectadas', sa.JSON(), nullable=True),
    sa.Column('inconsistencias', sa.JSON(), nullable=True),
    sa.Column('analizado_en', sa.DateTime(), nullable=True),
    sa.Column('score_final', sa.Float(), nullable=True),
    sa.Column('fecha_postulacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatos_email'), 'candidatos', ['email'], unique=False)
    op.create_index(op.f('ix_candidatos_estado'), 'candidatos', ['estado'], unique=False)
    op.create_index(op.f('ix_candidatos_tenant_id'), 'candidatos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_candidatos_vacante_id'), 'candidatos', ['vacante_id'], unique=False)
    op.create_table('entrevistas_ia',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidato_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plantilla_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_CURSO', 'FINALIZADA', 'EXPIRADA', name='estadoentrevista'), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('transcripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('dimensiones_json', sa.JSON(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevistas_ia_candidato_id'), 'entrevistas_ia', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_entrevistas_ia_estado'), 'entrevistas_ia', ['estado'], unique=False)
    op.create_index(op.f('ix_entrevistas_ia_plantilla_id'), 'entrevistas_ia', ['plantilla_id'], unique=False)
    op.create_index(op.f('ix_entrevistas_ia_tenant_id'), 'entrevistas_ia', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_entrevistas_ia_vacante_id'), 'entrevistas_ia', ['vacante_id'], unique=False)
    op.create_table('examenes',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidato_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacante_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sa.Enum('GENERANDO', 'PENDIENTE', 'EN_CURSO', 'FINALIZADO', 'EXPIRADO', name='estadoexamen'), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('semaforo', sa.Enum('VERDE', 'AMARILLO', 'ROJO', name='semaforoexamen'), nullable=False),
    sa.Column('puntaje_riesgo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examenes_candidato_id'), 'examenes', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_examenes_estado'), 'examenes', ['estado'], unique=False)
    op.create_index(op.f('ix_examenes_tenant_id'), 'examenes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_examenes_vacante_id'), 'examenes', ['vacante_id'], unique=False)
    op.create_table('notas_candidato',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidato_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('autor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_candidato_autor_id'), 'notas_candidato', ['autor_id'], unique=False)
    op.create_index(op.f('ix_notas_candidato_candidato_id'), 'notas_candidato', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_notas_candidato_tenant_id'), 'notas_candidato', ['tenant_id'], unique=False)
    op.create_table('tokens_acceso',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidato_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_corto', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('tipo', sa.Enum('EXAMEN', 'ENTREVISTA', name='tipotoken'), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidatos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_corto')
    )
    op.create_index(op.f('ix_tokens_acceso_candidato_id'), 'tokens_acceso', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_tokens_acceso_tenant_id'), 'tokens_acceso', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tokens_acceso_token'), 'tokens_acceso', ['token'], unique=True)
    op.create_table('capturas_auditoria',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entrevista_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sa.Enum('IDENTIDAD', 'PERIODICA', 'SOSPECHOSA', name='tipocaptura'), nullable=False),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrevista_id'], ['entrevistas_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capturas_auditoria_entrevista_id'), 'capturas_auditoria', ['entrevista_id'], unique=False)
    op.create_index(op.f('ix_capturas_auditoria_tenant_id'), 'capturas_auditoria', ['tenant_id'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examen_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entrevista_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severidad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='severidadevento'), nullable=False),
    sa.Column('detalle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrevista_id'], ['entrevistas_ia.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_auditoria_entrevista_id'), 'eventos_auditoria', ['entrevista_id'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_examen_id'), 'eventos_auditoria', ['examen_id'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_tenant_id'), 'eventos_auditoria', ['tenant_id'], unique=False)
    op.create_table('preguntas_examen',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examen_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MULTIPLE_CHOICE', 'ABIERTA', name='tipopregunta'), nullable=False),
    sa.Column('enunciado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opciones_json', sa.JSON(), nullable=True),
    sa.Column('respuesta_correcta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('respuesta_candidato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('puntos_max', sa.Float(), nullable=False),
    sa.Column('puntos_obtenidos', sa.Float(), nullable=True),
    sa.Column('feedback_ia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_examen_examen_id'), 'preguntas_examen', ['examen_id'], unique=False)
    op.create_index(op.f('ix_preguntas_examen_tenant_id'), 'preguntas_examen', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preguntas_examen_tenant_id'), table_name='preguntas_examen')
    op.drop_index(op.f('ix_preguntas_examen_examen_id'), table_name='preguntas_examen')
    op.drop_table('preguntas_examen')
    op.drop_index(op.f('ix_eventos_auditoria_tenant_id'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_examen_id'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_entrevista_id'), table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index(op.f('ix_capturas_auditoria_tenant_id'), table_name='capturas_auditoria')
    op.drop_index(op.f('ix_capturas_auditoria_entrevista_id'), table_name='capturas_auditoria')
    op.drop_table('capturas_auditoria')
    op.drop_index(op.f('ix_tokens_acceso_token'), table_name='tokens_acceso')
    op.drop_index(op.f('ix_tokens_acceso_tenant_id'), table_name='tokens_acceso')
    op.drop_index(op.f('ix_tokens_acceso_candidato_id'), table_name='tokens_acceso')
    op.drop_table('tokens_acceso')
    op.drop_index(op.f('ix_notas_candidato_tenant_id'), table_name='notas_candidato')
    op.drop_index(op.f('ix_notas_candidato_candidato_id'), table_name='notas_candidato')
    op.drop_index(op.f('ix_notas_candidato_autor_id'), table_name='notas_candidato')
    op.drop_table('notas_candidato')
    op.drop_index(op.f('ix_examenes_vacante_id'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_tenant_id'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_estado'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_candidato_id'), table_name='examenes')
    op.drop_table('examenes')
    op.drop_index(op.f('ix_entrevistas_ia_vacante_id'), table_name='entrevistas_ia')
    op.drop_index(op.f('ix_entrevistas_ia_tenant_id'), table_name='entrevistas_ia')
    op.drop_index(op.f('ix_entrevistas_ia_plantilla_id'), table_name='entrevistas_ia')
    op.drop_index(op.f('ix_entrevistas_ia_estado'), table_name='entrevistas_ia')
    op.drop_index(op.f('ix_entrevistas_ia_candidato_id'), table_name='entrevistas_ia')
    op.drop_table('entrevistas_ia')
    op.drop_index(op.f('ix_candidatos_vacante_id'), table_name='candidatos')
    op.drop_index(op.f('ix_candidatos_tenant_id'), table_name='candidatos')
    op.drop_index(op.f('ix_candidatos_estado'), table_name='candidatos')
    op.drop_index(op.f('ix_candidatos_email'), table_name='candidatos')
    op.drop_table('candidatos')
    op.drop_index(op.f('ix_vacantes_tenant_id'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_estado'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_codigo'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_area_id'), table_name='vacantes')
    op.drop_table('vacantes')
    op.drop_index(op.f('ix_dimensiones_evaluacion_tenant_id'), table_name='dimensiones_evaluacion')
    op.drop_index(op.f('ix_dimensiones_evaluacion_plantilla_id'), table_name='dimensiones_evaluacion')
    op.drop_table('dimensiones_evaluacion')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tags_tenant_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_plantillas_evaluacion_tenant_id'), table_name='plantillas_evaluacion')
    op.drop_table('plantillas_evaluacion')
    op.drop_index(op.f('ix_empresas_tenant_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_areas_tenant_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_codigo_corto'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
